export interface Hadith {
  id: number;
  arabic: string;
  english: string;
  narrator: string;
  source: string;
  category?: string;
}

export const NAWAWI_40: Hadith[] = [
  {
    id: 1,
    arabic: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    english: 'Actions are but by intentions, and every man shall have only that which he intended.',
    narrator: 'Umar ibn Al-Khattab',
    source: 'Bukhari & Muslim',
    category: 'Intentions',
  },
  {
    id: 2,
    arabic: 'الْإِسْلَامُ أَنْ تَشْهَدَ أَنْ لَا إِلَهَ إِلَّا اللهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللهِ، وَتُقِيمَ الصَّلَاةَ، وَتُؤْتِيَ الزَّكَاةَ، وَتَصُومَ رَمَضَانَ، وَتَحُجَّ الْبَيْتَ إِنِ اسْتَطَعْتَ إِلَيْهِ سَبِيلًا',
    english: 'Islam is that you testify that there is no god but Allah and that Muhammad is the Messenger of Allah, that you establish the prayer, pay the zakat, fast Ramadan, and perform the Hajj of the House if you are able to do so.',
    narrator: 'Umar ibn Al-Khattab',
    source: 'Muslim',
    category: 'Pillars of Islam',
  },
  {
    id: 3,
    arabic: 'بُنِيَ الْإِسْلَامُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلَاةِ، وَإِيتَاءِ الزَّكَاةِ، وَالْحَجِّ، وَصَوْمِ رَمَضَانَ',
    english: 'Islam is built upon five: testimony that there is no god but Allah and Muhammad is His Messenger, establishing prayer, giving zakat, Hajj, and fasting Ramadan.',
    narrator: 'Ibn Umar',
    source: 'Bukhari & Muslim',
    category: 'Pillars of Islam',
  },
  {
    id: 4,
    arabic: 'مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ، فَهُوَ رَدٌّ',
    english: 'Whoever introduces into this affair of ours that which is not part of it, it will be rejected.',
    narrator: 'Aisha',
    source: 'Bukhari & Muslim',
    category: 'Innovation',
  },
  {
    id: 5,
    arabic: 'مَنْ عَمِلَ عَمَلًا لَيْسَ عَلَيْهِ أَمْرُنَا فَهُوَ رَدٌّ',
    english: 'Whoever does an action which is not according to our matter, it will be rejected.',
    narrator: 'Aisha',
    source: 'Muslim',
    category: 'Innovation',
  },
  {
    id: 6,
    arabic: 'إِنَّ الْحَلَالَ بَيِّنٌ وَإِنَّ الْحَرَامَ بَيِّنٌ وَبَيْنَهُمَا أُمُورٌ مُشْتَبِهَاتٌ لَا يَعْلَمُهُنَّ كَثِيرٌ مِنَ النَّاسِ',
    english: 'The halal is clear and the haram is clear, and between them are doubtful matters which many people do not know about.',
    narrator: 'Nu\'man ibn Bashir',
    source: 'Bukhari & Muslim',
    category: 'Halal & Haram',
  },
  {
    id: 7,
    arabic: 'الدِّينُ النَّصِيحَةُ',
    english: 'The religion is sincere advice/counsel.',
    narrator: 'Tamim Al-Dari',
    source: 'Muslim',
    category: 'Advice',
  },
  {
    id: 8,
    arabic: 'أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَشْهَدُوا أَنْ لَا إِلَهَ إِلَّا اللهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللهِ، وَيُقِيمُوا الصَّلَاةَ، وَيُؤْتُوا الزَّكَاةَ',
    english: 'I have been commanded to fight the people until they testify that there is no god but Allah and that Muhammad is the Messenger of Allah, and until they establish prayer and pay zakat.',
    narrator: 'Ibn Umar',
    source: 'Bukhari & Muslim',
    category: 'Jihad',
  },
  {
    id: 9,
    arabic: 'مَا نَهَيْتُكُمْ عَنْهُ فَاجْتَنِبُوهُ، وَمَا أَمَرْتُكُمْ بِهِ فَأْتُوا مِنْهُ مَا اسْتَطَعْتُمْ',
    english: 'Whatever I have forbidden you from, avoid it, and whatever I have commanded you with, do as much of it as you are able.',
    narrator: 'Abu Hurairah',
    source: 'Bukhari & Muslim',
    category: 'Obedience',
  },
  {
    id: 10,
    arabic: 'إِنَّ اللَّهَ طَيِّبٌ لَا يَقْبَلُ إِلَّا طَيِّبًا',
    english: 'Allah is pure and He only accepts that which is pure.',
    narrator: 'Abu Hurairah',
    source: 'Muslim',
    category: 'Purity',
  },
  {
    id: 11,
    arabic: 'دَعْ مَا يَرِيبُكَ إِلَى مَا لَا يَرِيبُكَ',
    english: 'Leave that which makes you doubt for that which does not make you doubt.',
    narrator: 'Hasan ibn Ali',
    source: 'Tirmidhi & Nasai',
    category: 'Doubt',
  },
  {
    id: 12,
    arabic: 'مِنْ حُسْنِ إِسْلَامِ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ',
    english: 'Part of the excellence of a person\'s Islam is that he leaves alone that which does not concern him.',
    narrator: 'Abu Hurairah',
    source: 'Tirmidhi & Ibn Majah',
    category: 'Character',
  },
  {
    id: 13,
    arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    english: 'None of you truly believes until he loves for his brother what he loves for himself.',
    narrator: 'Anas ibn Malik',
    source: 'Bukhari & Muslim',
    category: 'Brotherhood',
  },
  {
    id: 14,
    arabic: 'لَا يَحِلُّ دَمُ امْرِئٍ مُسْلِمٍ إِلَّا بِإِحْدَى ثَلَاثٍ: الثَّيِّبُ الزَّانِي، وَالنَّفْسُ بِالنَّفْسِ، وَالتَّارِكُ لِدِينِهِ الْمُفَارِقُ لِلْجَمَاعَةِ',
    english: 'The blood of a Muslim may not be shed except in three cases: the married fornicator, a life for a life, and the one who forsakes his religion and separates from the community.',
    narrator: 'Ibn Masud',
    source: 'Bukhari & Muslim',
    category: 'Justice',
  },
  {
    id: 15,
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    english: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
    narrator: 'Abu Hurairah',
    source: 'Bukhari & Muslim',
    category: 'Speech',
  },
  {
    id: 16,
    arabic: 'لَا تَغْضَبْ',
    english: 'Do not become angry.',
    narrator: 'Abu Hurairah',
    source: 'Bukhari',
    category: 'Character',
  },
  {
    id: 17,
    arabic: 'إِنَّ اللَّهَ كَتَبَ الْإِحْسَانَ عَلَى كُلِّ شَيْءٍ',
    english: 'Verily Allah has prescribed excellence in everything.',
    narrator: 'Shaddad ibn Aws',
    source: 'Muslim',
    category: 'Excellence',
  },
  {
    id: 18,
    arabic: 'اتَّقِ اللهَ حَيْثُمَا كُنْتَ، وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
    english: 'Fear Allah wherever you are. Follow up a bad deed with a good one and it will wipe it out. And deal with people with good character.',
    narrator: 'Abu Dharr & Muadh',
    source: 'Tirmidhi',
    category: 'Taqwa',
  },
  {
    id: 19,
    arabic: 'احْفَظِ اللهَ يَحْفَظْكَ، احْفَظِ اللهَ تَجِدْهُ تُجَاهَكَ',
    english: 'Be mindful of Allah and He will protect you. Be mindful of Allah and you will find Him in front of you.',
    narrator: 'Ibn Abbas',
    source: 'Tirmidhi',
    category: 'Taqwa',
  },
  {
    id: 20,
    arabic: 'إِذَا لَمْ تَسْتَحِ فَاصْنَعْ مَا شِئْتَ',
    english: 'If you feel no shame, then do as you wish.',
    narrator: 'Abu Masud',
    source: 'Bukhari',
    category: 'Modesty',
  },
];

export const HADITH_OF_THE_DAY_POOL: { arabic: string; english: string; source: string }[] = [
  { arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ', english: 'The best of you are those who learn the Quran and teach it.', source: 'Bukhari' },
  { arabic: 'الصَّلَاةُ عِمَادُ الدِّينِ', english: 'Prayer is the pillar of the religion.', source: 'Baihaqi' },
  { arabic: 'الطُّهُورُ شَطْرُ الْإِيمَانِ', english: 'Cleanliness is half of faith.', source: 'Muslim' },
  { arabic: 'أَفْضَلُ الذِّكْرِ لَا إِلَهَ إِلَّا اللَّهُ', english: 'The best of dhikr is: There is no god but Allah.', source: 'Tirmidhi' },
  { arabic: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ', english: 'A Muslim is one from whose tongue and hand the Muslims are safe.', source: 'Bukhari' },
  { arabic: 'ابْتَغُوا الرِّزْقَ فِي خَبَايَا الْأَرْضِ', english: 'Seek provision in the hidden places of the earth.', source: 'Bayhaqi' },
  { arabic: 'مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ كَمَثَلِ الْجَسَدِ الْوَاحِدِ', english: 'The believers in their mutual love are like one body.', source: 'Bukhari & Muslim' },
];
