export interface NameOfAllah {
  number: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  reference: string;
}

export const NAMES_OF_ALLAH: NameOfAllah[] = [
  { number: 1, arabic: 'الله', transliteration: 'Allah', meaning: 'The One Worthy of All Worship', reference: 'Quran 1:1' },
  { number: 2, arabic: 'الرَّحْمَن', transliteration: 'Ar-Rahman', meaning: 'The Most Compassionate', reference: 'Quran 1:3' },
  { number: 3, arabic: 'الرَّحِيم', transliteration: 'Ar-Rahim', meaning: 'The Most Merciful', reference: 'Quran 1:3' },
  { number: 4, arabic: 'الْمَلِك', transliteration: 'Al-Malik', meaning: 'The Sovereign', reference: 'Quran 59:23' },
  { number: 5, arabic: 'الْقُدُّوس', transliteration: 'Al-Quddus', meaning: 'The Most Holy', reference: 'Quran 59:23' },
  { number: 6, arabic: 'السَّلَام', transliteration: 'As-Salam', meaning: 'The Source of Peace', reference: 'Quran 59:23' },
  { number: 7, arabic: 'الْمُؤْمِن', transliteration: "Al-Mu'min", meaning: 'The Grantor of Security', reference: 'Quran 59:23' },
  { number: 8, arabic: 'الْمُهَيْمِن', transliteration: 'Al-Muhaymin', meaning: 'The Guardian', reference: 'Quran 59:23' },
  { number: 9, arabic: 'الْعَزِيز', transliteration: 'Al-Aziz', meaning: 'The All-Mighty', reference: 'Quran 59:23' },
  { number: 10, arabic: 'الْجَبَّار', transliteration: 'Al-Jabbar', meaning: 'The Compeller', reference: 'Quran 59:23' },
  { number: 11, arabic: 'الْمُتَكَبِّر', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme', reference: 'Quran 59:23' },
  { number: 12, arabic: 'الْخَالِق', transliteration: 'Al-Khaliq', meaning: 'The Creator', reference: 'Quran 59:24' },
  { number: 13, arabic: 'الْبَارِئ', transliteration: "Al-Bari'", meaning: 'The Originator', reference: 'Quran 59:24' },
  { number: 14, arabic: 'الْمُصَوِّر', transliteration: 'Al-Musawwir', meaning: 'The Fashioner', reference: 'Quran 59:24' },
  { number: 15, arabic: 'الْغَفَّار', transliteration: 'Al-Ghaffar', meaning: 'The Repeatedly Forgiving', reference: 'Quran 20:82' },
  { number: 16, arabic: 'الْقَهَّار', transliteration: 'Al-Qahhar', meaning: 'The Subduer', reference: 'Quran 13:16' },
  { number: 17, arabic: 'الْوَهَّاب', transliteration: 'Al-Wahhab', meaning: 'The Bestower', reference: 'Quran 3:8' },
  { number: 18, arabic: 'الرَّزَّاق', transliteration: 'Ar-Razzaq', meaning: 'The Provider', reference: 'Quran 51:58' },
  { number: 19, arabic: 'الْفَتَّاح', transliteration: 'Al-Fattah', meaning: 'The Opener', reference: 'Quran 34:26' },
  { number: 20, arabic: 'الْعَلِيم', transliteration: 'Al-Alim', meaning: 'The All-Knowing', reference: 'Quran 2:158' },
  { number: 21, arabic: 'الْقَابِض', transliteration: 'Al-Qabid', meaning: 'The Withholder', reference: 'Quran 2:245' },
  { number: 22, arabic: 'الْبَاسِط', transliteration: 'Al-Basit', meaning: 'The Extender', reference: 'Quran 2:245' },
  { number: 23, arabic: 'الْخَافِض', transliteration: 'Al-Khafid', meaning: 'The Reducer', reference: 'Hadith' },
  { number: 24, arabic: 'الرَّافِع', transliteration: 'Ar-Rafi', meaning: 'The Exalter', reference: 'Hadith' },
  { number: 25, arabic: 'الْمُعِز', transliteration: "Al-Mu'izz", meaning: 'The Bestower of Honor', reference: 'Quran 3:26' },
  { number: 26, arabic: 'الْمُذِل', transliteration: 'Al-Mudhill', meaning: 'The Humiliator', reference: 'Quran 3:26' },
  { number: 27, arabic: 'السَّمِيع', transliteration: 'As-Sami', meaning: 'The All-Hearing', reference: 'Quran 2:127' },
  { number: 28, arabic: 'الْبَصِير', transliteration: 'Al-Basir', meaning: 'The All-Seeing', reference: 'Quran 4:58' },
  { number: 29, arabic: 'الْحَكَم', transliteration: 'Al-Hakam', meaning: 'The Judge', reference: 'Quran 22:69' },
  { number: 30, arabic: 'الْعَدْل', transliteration: 'Al-Adl', meaning: 'The Just', reference: 'Hadith' },
  { number: 31, arabic: 'اللَّطِيف', transliteration: 'Al-Latif', meaning: 'The Subtle One', reference: 'Quran 22:63' },
  { number: 32, arabic: 'الْخَبِير', transliteration: 'Al-Khabir', meaning: 'The All-Aware', reference: 'Quran 6:18' },
  { number: 33, arabic: 'الْحَلِيم', transliteration: 'Al-Halim', meaning: 'The Forbearing', reference: 'Quran 2:225' },
  { number: 34, arabic: 'الْعَظِيم', transliteration: 'Al-Azim', meaning: 'The Magnificent', reference: 'Quran 2:255' },
  { number: 35, arabic: 'الْغَفُور', transliteration: 'Al-Ghafur', meaning: 'The Forgiving', reference: 'Quran 2:173' },
  { number: 36, arabic: 'الشَّكُور', transliteration: 'Ash-Shakur', meaning: 'The Appreciative', reference: 'Quran 35:30' },
  { number: 37, arabic: 'الْعَلِيّ', transliteration: 'Al-Ali', meaning: 'The Most High', reference: 'Quran 2:255' },
  { number: 38, arabic: 'الْكَبِير', transliteration: 'Al-Kabir', meaning: 'The Greatest', reference: 'Quran 13:9' },
  { number: 39, arabic: 'الْحَفِيظ', transliteration: 'Al-Hafiz', meaning: 'The Preserver', reference: 'Quran 11:57' },
  { number: 40, arabic: 'الْمُقِيت', transliteration: 'Al-Muqit', meaning: 'The Sustainer', reference: 'Quran 4:85' },
  { number: 41, arabic: 'الْحَسِيب', transliteration: 'Al-Hasib', meaning: 'The Reckoner', reference: 'Quran 4:6' },
  { number: 42, arabic: 'الْجَلِيل', transliteration: 'Al-Jalil', meaning: 'The Majestic', reference: 'Quran 55:27' },
  { number: 43, arabic: 'الْكَرِيم', transliteration: 'Al-Karim', meaning: 'The Generous', reference: 'Quran 27:40' },
  { number: 44, arabic: 'الرَّقِيب', transliteration: 'Ar-Raqib', meaning: 'The Watchful', reference: 'Quran 4:1' },
  { number: 45, arabic: 'الْمُجِيب', transliteration: 'Al-Mujib', meaning: 'The Responsive', reference: 'Quran 11:61' },
  { number: 46, arabic: 'الْوَاسِع', transliteration: 'Al-Wasi', meaning: 'The All-Encompassing', reference: 'Quran 2:115' },
  { number: 47, arabic: 'الْحَكِيم', transliteration: 'Al-Hakim', meaning: 'The All-Wise', reference: 'Quran 2:129' },
  { number: 48, arabic: 'الْوَدُود', transliteration: 'Al-Wadud', meaning: 'The Loving', reference: 'Quran 11:90' },
  { number: 49, arabic: 'الْمَجِيد', transliteration: 'Al-Majid', meaning: 'The Glorious', reference: 'Quran 11:73' },
  { number: 50, arabic: 'الْبَاعِث', transliteration: "Al-Ba'ith", meaning: 'The Resurrector', reference: 'Quran 22:7' },
  { number: 51, arabic: 'الشَّهِيد', transliteration: 'Ash-Shahid', meaning: 'The Witness', reference: 'Quran 4:166' },
  { number: 52, arabic: 'الْحَق', transliteration: 'Al-Haqq', meaning: 'The Truth', reference: 'Quran 22:6' },
  { number: 53, arabic: 'الْوَكِيل', transliteration: 'Al-Wakil', meaning: 'The Trustee', reference: 'Quran 3:173' },
  { number: 54, arabic: 'الْقَوِيّ', transliteration: 'Al-Qawi', meaning: 'The All-Strong', reference: 'Quran 22:74' },
  { number: 55, arabic: 'الْمَتِين', transliteration: 'Al-Matin', meaning: 'The Firm', reference: 'Quran 51:58' },
  { number: 56, arabic: 'الْوَلِيّ', transliteration: 'Al-Wali', meaning: 'The Protecting Friend', reference: 'Quran 4:45' },
  { number: 57, arabic: 'الْحَمِيد', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy', reference: 'Quran 14:8' },
  { number: 58, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The Accountant', reference: 'Quran 72:28' },
  { number: 59, arabic: 'الْمُبْدِئ', transliteration: "Al-Mubdi'", meaning: 'The Originator', reference: 'Quran 10:34' },
  { number: 60, arabic: 'الْمُعِيد', transliteration: "Al-Mu'id", meaning: 'The Restorer', reference: 'Quran 10:34' },
  { number: 61, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life', reference: 'Quran 30:50' },
  { number: 62, arabic: 'الْمُمِيت', transliteration: 'Al-Mumit', meaning: 'The Taker of Life', reference: 'Quran 3:156' },
  { number: 63, arabic: 'الْحَيّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living', reference: 'Quran 2:255' },
  { number: 64, arabic: 'الْقَيُّوم', transliteration: 'Al-Qayyum', meaning: 'The Self-Subsisting', reference: 'Quran 2:255' },
  { number: 65, arabic: 'الْوَاجِد', transliteration: 'Al-Wajid', meaning: 'The Finder', reference: 'Hadith' },
  { number: 66, arabic: 'الْمَاجِد', transliteration: 'Al-Majid', meaning: 'The Noble', reference: 'Hadith' },
  { number: 67, arabic: 'الْوَاحِد', transliteration: 'Al-Wahid', meaning: 'The One', reference: 'Quran 13:16' },
  { number: 68, arabic: 'الأَحَد', transliteration: 'Al-Ahad', meaning: 'The Unique', reference: 'Quran 112:1' },
  { number: 69, arabic: 'الصَّمَد', transliteration: 'As-Samad', meaning: 'The Eternal', reference: 'Quran 112:2' },
  { number: 70, arabic: 'الْقَادِر', transliteration: 'Al-Qadir', meaning: 'The All-Powerful', reference: 'Quran 6:65' },
  { number: 71, arabic: 'الْمُقْتَدِر', transliteration: 'Al-Muqtadir', meaning: 'The Determiner', reference: 'Quran 18:45' },
  { number: 72, arabic: 'الْمُقَدِّم', transliteration: 'Al-Muqaddim', meaning: 'The Expediter', reference: 'Hadith' },
  { number: 73, arabic: 'الْمُؤَخِّر', transliteration: "Al-Mu'akhkhir", meaning: 'The Delayer', reference: 'Hadith' },
  { number: 74, arabic: 'الأَوَّل', transliteration: 'Al-Awwal', meaning: 'The First', reference: 'Quran 57:3' },
  { number: 75, arabic: 'الآخِر', transliteration: 'Al-Akhir', meaning: 'The Last', reference: 'Quran 57:3' },
  { number: 76, arabic: 'الظَّاهِر', transliteration: 'Az-Zahir', meaning: 'The Manifest', reference: 'Quran 57:3' },
  { number: 77, arabic: 'الْبَاطِن', transliteration: 'Al-Batin', meaning: 'The Hidden', reference: 'Quran 57:3' },
  { number: 78, arabic: 'الْوَالِي', transliteration: 'Al-Wali', meaning: 'The Governor', reference: 'Quran 13:11' },
  { number: 79, arabic: 'الْمُتَعَالِي', transliteration: "Al-Muta'ali", meaning: 'The Most Exalted', reference: 'Quran 13:9' },
  { number: 80, arabic: 'الْبَرّ', transliteration: 'Al-Barr', meaning: 'The Source of Goodness', reference: 'Quran 52:28' },
  { number: 81, arabic: 'التَّوَّاب', transliteration: 'At-Tawwab', meaning: 'The Acceptor of Repentance', reference: 'Quran 2:37' },
  { number: 82, arabic: 'الْمُنْتَقِم', transliteration: 'Al-Muntaqim', meaning: 'The Avenger', reference: 'Quran 32:22' },
  { number: 83, arabic: 'الْعَفُوّ', transliteration: "Al-Afuw'", meaning: 'The Pardoner', reference: 'Quran 4:99' },
  { number: 84, arabic: 'الرَّؤُوف', transliteration: "Ar-Ra'uf", meaning: 'The Compassionate', reference: 'Quran 2:143' },
  { number: 85, arabic: 'مَالِكُ الْمُلْك', transliteration: 'Malik Al-Mulk', meaning: 'Owner of All Sovereignty', reference: 'Quran 3:26' },
  { number: 86, arabic: 'ذُو الْجَلالِ وَالإِكْرَام', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'Lord of Majesty and Generosity', reference: 'Quran 55:27' },
  { number: 87, arabic: 'الْمُقْسِط', transliteration: 'Al-Muqsit', meaning: 'The Equitable', reference: 'Quran 7:29' },
  { number: 88, arabic: 'الْجَامِع', transliteration: 'Al-Jami', meaning: 'The Gatherer', reference: 'Quran 3:9' },
  { number: 89, arabic: 'الْغَنِيّ', transliteration: 'Al-Ghani', meaning: 'The Self-Sufficient', reference: 'Quran 2:263' },
  { number: 90, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher', reference: 'Quran 9:28' },
  { number: 91, arabic: 'الْمَانِع', transliteration: "Al-Mani'", meaning: 'The Preventer', reference: 'Hadith' },
  { number: 92, arabic: 'الضَّار', transliteration: 'Ad-Darr', meaning: 'The Distresser', reference: 'Hadith' },
  { number: 93, arabic: 'النَّافِع', transliteration: 'An-Nafi', meaning: 'The Benefiter', reference: 'Hadith' },
  { number: 94, arabic: 'النُّور', transliteration: 'An-Nur', meaning: 'The Light', reference: 'Quran 24:35' },
  { number: 95, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide', reference: 'Quran 25:31' },
  { number: 96, arabic: 'الْبَدِيع', transliteration: "Al-Badi'", meaning: 'The Originator', reference: 'Quran 2:117' },
  { number: 97, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Everlasting', reference: 'Quran 87:17' },
  { number: 98, arabic: 'الْوَارِث', transliteration: 'Al-Warith', meaning: 'The Inheritor', reference: 'Quran 15:23' },
  { number: 99, arabic: 'الرَّشِيد', transliteration: 'Ar-Rashid', meaning: 'The Guide to Right Path', reference: 'Quran 11:87' },
];
